ru:
  already_setup: Я уже настроен
  started:
    - Работаем
    - Введите / чтобы увидеть все команды
  scan: 
    - Зачем будить? Вообще-то, в вашем канале сидит маленький китаец и бросает кости. Постыдитесь.
    - Ты пидор, %{param}!
  scan_already_done:
    - Китаец просыпается... Сверяет данные...
    - Сегодня уже проводился розыгрыш, спешить некуда! %{param} все еще пидорасина. Китаец продолжает спать.
  time_left: Осталось %{hours} часов и %{minutes} минут
  nobody_to_scan: Никто не зарегестрировался, так что пидорасы все!
  last_scan:
    - Секунду, сверяю данные
    - Последний пидор %{param}
  no_last_scan: Никто))0)
  results: Не спится, животные...
  register:
    - Сек, открою эксель файл
    - Тебя зарегестрировано, %{param}
  already_registered: Ты уже зарегистрирован, %{param}!
  not_started: Нужно написать /start сначала
  not_registered: Нет пидоров!
  last_pidors: "Последние пидоры:"
  yoloxd:
    - Сука, угадал
    - Твои очки анулированы, гений.
  reminder:
    - Внимание! Напоминаю, что уже есть возможность сканировать!
  confirm_subscription:
    - Супер, еще работа
    - Нет чтобы самим следить за временем. Ленивые засранцы
    - Ладно, напомню следующий раз когда придет время сканировать
  already_subscribed: Вы уже подписаны на напоминание!
  no_subscription: Вы не подписаны на напоминание!
  confirm_unsubscription: Спасибо за отписку, неблагодарные
