ru:
  already_setup: Я уже настроен
  started:
    - Работаем
    - Введите / чтобы увидеть все команды
  scan: 
    - Зачем будить? Вообще-то, в вашем канале сидит маленький китаец и бросает кости. Постыдитесь.
    - Ты пидор, %{param}!
  scan_already_done:
    - Китаец просыпается... Сверяет данные...
    - Сегодня уже проводился розыгрыш, спешить некуда! %{param} все еще пидорасина. Китаец продолжает спать.
  time_left: Осталось %{hours} часов и %{minutes} минут
  nobody_to_scan: Никто не зарегестрировался, так что пидорасы все!
  last_scan:
    - Секунду, сверяю данные
    - Последний пидор %{param}
  no_last_scan: Никто))0)
  results: Не спится, животные...
  register:
    - Сек, открою эксель файл
    - Тебя зарегестрировано, %{param}
  already_registered: Ты уже зарегистрирован, %{param}!
  not_started: Нужно написать /start сначала
  not_registered: Нет пидоров!
  last_pidors: "Последние пидоры:"
  yoloxd:
    - Сука, угадал
    - Твои очки анулированы, гений.
  reminder:
    - Внимание! Напоминаю, что уже есть возможность сканировать!
  confirm_subscription:
    - Супер, еще работа
    - Нет чтобы самим следить за временем. Ленивые засранцы
    - Ладно, напомню следующий раз когда придет время сканировать
  already_subscribed: Вы уже подписаны на напоминание!
  no_subscription: Вы не подписаны на напоминание!
  confirm_unsubscription: Спасибо за отписку, неблагодарные
  no_such_locale: "Этот язык еще не установлен. Пожалуйста, отправьте запрос на создание этого языка создателю: @bars_eek. Доступные языки: %{param}"
  locale_changed: Хорошо, теперь я буду говорить на языке %{param}

en:
  already_setup: I am already setup
  started:
    - Now we're talking
    - Enter / to see all commands
  scan:
    - So... Why'd you wake me up? FYI, there is a teenager chinese rolling dice in this channel. Shame on you.
    - You're faggot, %{param}!
  scan_already_done:
    - Chinese teenager wakes up... checks the data...
    - Scan has already been done today, no need to hurry! %{param} is still a faggot. Chinese teenager goes back to sleep.
  time_left: "%{hours} hours and %{minutes} minutes left"
  nobody_to_scan: Nobody is registered, so everybody is a faggot!
  last_scan:
    - One sec, checking the data
    - Last faggot is %{param}
  no_last_scan: Nobody))0)
  results: Why aren't you asleep, don't you have anything better to do? You don't, do you? Poor little thing...
  register:
    - One sec, opening an excel file
    - You're now registered, %{param}
  already_registered: You've already been registered, %{param}!
  not_started: Need to write /start first
  not_registered: No faggots yet!
  last_pidors: "Last faggots:"
  yoloxd:
    - You guessed it, little fuck...
    - Твои очки анулированы, гений. Your points are nullified, genius.
  reminder:
    - Attention! The scan is available!
  confirm_subscription:
    - Great, more work
    - Why can't you keep track of time yourself, lazy bastards
    - Aight, I will remind you next time the scan is available
  already_subscribed: You are already subscribed to a reminder!
  no_subscription: You aren't yet subscribed to a reminder!
  confirm_unsubscription: Thanks for unsubscribtion, you thankless wights
  no_such_locale: "This language is not yet available. Please, send a feature request to the creator of this bot: @bars_eek. Available locales are: %{param}"
  locale_changed: Ok, now I will speak language %{param}

nl:
  already_setup: Ik ben already opgeset
  started:
    - Welkom naar NEDERLAND, je moet je binnen 2 weken na aankomst inschrijven bij de gemeente
    - U kunt / klikken (flikken haha) om de commando's te zien
  scan:
    - Wat, waarom hat u me opgewaken? Kanker, godverdomme!
    - Gefeliciteerd! Je bent een flikker, %{param}!
  scan_already_done:
    - Ik kalkuleere de GAY
    - Chill broeder, neem een spliff. %{param} is een flikker nog een tijdje.
  time_left: "%{hours}:%{minutes} tot de volgende pride"
  nobody_to_scan: Niemand is geregistreerd, jullie zijn allemaal flikkertjes!
  last_scan:
    - Kalkuleert...
    - Momenteel is %{param} de burgemeester van gaytown
  no_last_scan: Nobody))0)
  results: Waarom slaap je niet? Ga je inschrijven bij de gemeente 
  register:
    - Je staat ingeschreven bij de gemeente... 
    - Je bent nu officieel woonachtig in Maastricht, %{param}
  already_registered: De gemeente heeft uw gegevens al, %{param}!
  not_started: Je moet eerst "/start" schrijven, stoned domkop
  not_registered: Nog geen Belg-eehm flikkertjes!
  last_pidors: "Zedendelinquent register:"
  yoloxd:
    - Glorie aan de koning...
    - Je homokaart is ingetrokken, genie.
  reminder:
    - Alle burgers opgelet, gratis homotests zijn nu beschikbaar voor iedereen met symptomen!
  confirm_subscription:
    - Verdomme, ik heb net lsd genomen, oké, laten we dit snel doen
    - Wil je een tab?
    - K, ik zal het je vertellen als ik nuchter genoeg ben om weer te werken 
  already_subscribed: Ik struikel ballen bro, laat me met rust!
  no_subscription: You aren't yet subscribed to a reminder!
  confirm_unsubscription: Thanks for unsubscribtion, you thankless wights
  no_such_locale: "Waarom wissel je van taal? Ben je een verrader? Je mag maar een van de volgende dingen zeggen: %{param}, anders, ga zeuren naar @bars_eek."
  locale_changed: Nederland neemt afscheid van je, pas op dat je niet "per ongeluk" wat MDMA in je schoenen vergeet, de %{param} autoriteiten zullen niet amuseren. 
